version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: N17382965-5
      MYSQL_DATABASE: integracionecomerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: N17382965-5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge